### ISSUE TITLE
undefined method `resource_class' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by poudelprakash** [burigems/buriauth#25]
app wont start after installing this gem in rails 7 app
## Bug report

nimble-auth/lib/nimble_auth/resource_setup.rb:12:in `extend_user_model': undefined method `resource_class' for nil:NilClass (NoMethodError)

```
from /Users/prakash/workspaces/2021/invoice_work/engines/nimble-auth/lib/nimble_auth/engine.rb:21:in `block in <class:Engine>'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:415:in `instance_exec'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:415:in `block in make_lambda'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:592:in `block (2 levels) in default_terminator'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:591:in `catch'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:591:in `block in default_terminator'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:200:in `block in halting'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:500:in `block in invoke_before'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:500:in `each'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:500:in `invoke_before'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:106:in `run_callbacks'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/reloader.rb:88:in `prepare!'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/initializable.rb:32:in `run'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/application.rb:369:in `initialize!'
	from /Users/prakash/workspaces/2021/invoice_work/config/environment.rb:5:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.0.beta4/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:36:in `start'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/command/base.rb:87:in `perform'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/command.rb:48:in `invoke'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands.rb:18:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from bin/rails:4:in `<main>'
	```

**Comment by poudelprakash** [comment]
This error was occuring due to missing nimble-auth initializer in my project. Closing this
